### ISSUE TITLE
Error Trying to Use Mindrove in Python executable

### ISSUE THREAD

**Issue by justinlxiang** [MindRove/MindRoveSDK#11]
Hi, I am trying to build a python executable which includes mindrove==0.0.10 as one of the libraries in pip list and built it uses pyinstaller. When I tried to run the executable, I got this error below. Is there any way to fix this. For reference, I have an app.py that imports mindrove and collects the data from the board and I ran this command to build the executable: pyinstaller --onefile app.py

An error occurred: Dynamic library /var/folders/q2/7qs8zs4x77x62hpy06nrqhr80000gn/T/_MEIB4TM2S/mindrove/lib/libBoardController.dylib is missed, did you forget to compile MindRove before installation of python package?

**Comment by MindRove** [comment]
Hi. 
@justinlxiang, thanks for the information about this issue.
We'll try to reproduce the problem. Due to the summer holidays, our capacity for working on this is limited until next week, but we'll see what we can do.

In the meantime, could you please provide the following details?
- What is the type and version of the OS you use for creating the executable?
- What other Python libraries does your app.py use? If this information is confidential, let's discuss it by email (info@mindrove.com).

Regards,
Gergely

**Comment by justinlxiang** [comment]
MacOS 14.5
Package                   Version
------------------------- -----------
altgraph                  0.17.4
blinker                   1.8.2
click                     8.1.7
Flask                     3.0.3
Flask-Cors                4.0.1
Flask-SQLAlchemy          3.1.1
itsdangerous              2.2.0
Jinja2                    3.1.4
joblib                    1.4.2
macholib                  1.16.3
MarkupSafe                2.1.5
mindrove                  0.0.10
nptyping                  1.4.4
numpy                     1.24.3
packaging                 24.1
pandas                    2.2.2
pbkdf2                    1.3
pip                       24.0
pyinstaller               6.9.0
pyinstaller-hooks-contrib 2024.8
python-dateutil           2.9.0.post0
pytz                      2024.1
scikit-learn              1.5.1
scipy                     1.13.1
setuptools                65.5.0
six                       1.16.0
SQLAlchemy                2.0.32
threadpoolctl             3.5.0
typing_extensions         4.12.2
typish                    1.9.3
tzdata                    2024.1
Werkzeug                  3.0.3
wifi                      0.3.8

**Comment by justinlxiang** [comment]
This was the code I was running where I think the error occurs as I did not get an import error. 
      BoardShim.enable_dev_board_logger()
      params = MindRoveInputParams()
      board_id = BoardIds.MINDROVE_WIFI_BOARD
      board_shim = BoardShim(board_id, params)

      emg_channels = BoardShim.get_emg_channels(board_id)
      gyro_channels = BoardShim.get_gyro_channels(board_id)
      accel_channels = BoardShim.get_accel_channels(board_id)
      timestamp_channel = BoardShim.get_timestamp_channel(board_id)
      sampling_rate = BoardShim.get_sampling_rate(board_id)

      board_shim.prepare_session()
      board_shim.start_stream()
