### ISSUE TITLE
Synchronizing Mindrove with Other Hardware

### ISSUE THREAD

**Issue by mj-sam** [MindRove/MindRoveSDK#12]
Platform: Linux
Language: C#

I am currently working on a project with MindRove to stream data over LSL for synchronization with other devices. However, I am facing some challenges:

1. Clock Synchronization
Is it possible to synchronize the internal clock of the MindRove device with my laptop? If so, what is the recommended approach?

2. Documentation Clarification
The purpose of the "beep" and "boop" signals is unclear in the documentation. Could you provide more details about their function?

3. Channel Description
I receive data with 30 channels, but the documentation lacks clarity on their descriptions. For example:

Channels 20, 21, and 22 are from the accelerometer.
Channels 23, 24, and 25 are from the magnetometer.
However, I need clarification on which dimension corresponds to x, y, and z for these sensors.

Additional Context
I’m working on a tight deadline, so a prompt response would be greatly appreciated :)

Thank you in advance!

**Comment by MindRove** [comment]
Hi.

We recommend using the "beep" and "boop" triggers to synchronize clocks. For example, you could send a "beep" signal to the device every minute and log the exact timestamp on your laptop when each signal is sent. The beep signals will register on the device’s trigger channel, with a delay of under 4 milliseconds from when the command is issued. This method will give you a synchronization accuracy of about 4 milliseconds with your laptop. At the time when the beep signal is received by the device, the value of its trigger channel will be 1, when the boop is received. Between these signals, the trigger channel will remain at 0.

For detailed information about the IMU sensor’s placement and orientation, please refer to the user manual in the Visualizer on Desktop software. ([link](https://mindrove.com/downloads/)).

Could you clarify where you found this channel mapping information?
Channels 20, 21, and 22 are from the accelerometer.
Channels 23, 24, and 25 are from the magnetometer.

**Comment by rokaijano** [comment]
Hi, 

Also for further clarification: 

Accelerometer data: (20,21,22) -> (x,y,z)
**Gyroscope** data : (23,24,25) -> (x,y,z)

Please refer to the link above for the actual, physical axis of these dimensions.

**Comment by mj-sam** [comment]
Many thanks for the prompt replies!

> Could you clarify where you found this channel mapping information?

In my implementation (`board_shim.get_board_data(num_points);`), the data has a shape of (30, time). Using `BoardShim.get_accel_channels(board_id)` I can locate the accelerometer channels as indices 20, 21, and 22. For channels 23, 24, and 25, with visual inspection the values align only if I assume these are Gyroscope data.

According to my understanding, I should calculate an offset for each chunk of time and then synchronize my signal, similar to the image below.

![photo_2024-10-29_16-06-01](https://github.com/user-attachments/assets/2224f5c3-9b81-461a-8753-7bfb51fa7588)

**Comment by MindRove** [comment]
Sorry, I can't quite understand the image and the formula. But please note that the time it takes for the trigger signal to arrive at the device from the laptop and get registered is usually a maximum of 4 msec, so not exactly 4 msec every time. It can be sometimes 1 msec, sometimes 4 msec. That's why the limitation for the synchronization is approximately 4 msec.

**Comment by mj-sam** [comment]
Thank you very much for the clarification. I was too focused on achieving ideal synchronization without any delay. I now understand the practical limitations of exact synchronization and realize that achieving sub-4ms precision may not be feasible.

Additionally, I am having difficulty finding the correct command in C# to send the "beep" signal to the device. Could you please provide guidance on the specific command or syntax for this?

Thank you in advance.

**Comment by rokaijano** [comment]
You can use the following command: 

`board_shim.config_board (BoardShim.MindroveWifiConfigMode.BEEP);`

under the _BoardShim.MindroveWifiConfigMode_ you can find the other options as well.

**Comment by mj-sam** [comment]
I appreciate your quick responses and assistance! I believe there may be an issue on my end; however, I’ve noticed that while the code functions correctly in Python, there seems to be no corresponding variable under the same name in C#. Additionally, I am currently working with SDK version 3.0.

**Comment by rokaijano** [comment]
Hi, 
Thanks for the info. As a quick fix, try downloading the **mindrove** nuget package and checking that way as well. Please note that aside from the **mindrove.dll**, the rest of the .dll files should still be copied manually to the build directory.
Let us know if it works this way.
