### ISSUE TITLE
Impossible to run anything in Python

### ISSUE THREAD

**Issue by torc16** [MindRove/MindRoveSDK#13]
Language: Python
OS: Tried on Mac and Windows

It is impossible to do anything in Python. 

I just did: 
`pip install -U mindrove`
then: 
`from mindrove.board_shim import BoardShim, MindRoveInputParams, BoardIds`
`BoardShim.enable_dev_board_logger()`

And I get the error: 
`OSError: /usr/local/lib/python3.10/dist-packages/mindrove/lib/libBoardController.so: cannot open shared object file: No such file or directory`.

**Comment by MindRove** [comment]
Hi. 
We found an issue that could cause a problem in some environments, and hopefully fixed it in the new version (3.0.1). Could you please pip-install it and check whether the error persists? 
pip install -U mindrove 
should install the 3.0.1 version now.

**Comment by torc16** [comment]
Thank you, it is working
