### ISSUE TITLE
Not same values when using the app and SDK

### ISSUE THREAD

**Issue by sofiahernandezp** [MindRove/MindRoveSDK#4]
I'm trying to retrieve data from the device using the SDK python codes. However, when compared to the data acquired through the application itself, the values are very different. Additionally, in the data acquired from the application when performing different gestures, it shows very evident peaks for each gesture, which is not the case with the Python code. It shows undefined signals regardless of the gesture being performed. I have attached two images, one showing the data obtained through the application, and the other showing the data obtained from the SDK. It has been confirmed that everything is perfectly connected, but the source of this significant difference is unknown.
Data obtained from the app:
![output](https://github.com/MindRove/MindRoveSDK/assets/124250001/00015e2b-860e-42c1-bc6b-40146bb3e2ba)
settings from the app:.
![settingapp](https://github.com/MindRove/MindRoveSDK/assets/124250001/18121ef3-93c9-45f6-bf34-c2ea64599234)

Data obtained from SDK:
![cap](https://github.com/MindRove/MindRoveSDK/assets/124250001/8b0bf704-658e-41f0-b005-c5dd7fdc2825)

Settings from SDK:
![1](https://github.com/MindRove/MindRoveSDK/assets/124250001/b63c7b50-e10c-4cca-9cf9-e475b693f611)
![2](https://github.com/MindRove/MindRoveSDK/assets/124250001/4180e2b5-6d66-4702-ad03-3c7305cb56b3)
![Uploading 3.png…]()

**Comment by MindRove** [comment]
Hi. The timescale seems to be different in the two graphs: 100 seconds for the app, and 5 seconds for the SDK. Could you show the SDK data from a 100 sec period?

Moreover, in the SDK you seemingly do not use any filters, while in the app the DC filter is switched on.
